In [1]:
#Importing relevant python library
import pandas as pd

In [2]:
#Reading CSVs using pandas into dataframes
matches_df = pd.read_csv('data/matches_data.csv')
batting_df = pd.read_csv('data/batting_data.csv')
bowling_df = pd.read_csv('data/bowling_data.csv')

In [3]:
matches_df.head()

,Unnamed: 0,Team1,Team2,Winner,Margin,Ground,Date,Match_id,URL
0,1,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823,https://www.espncricinfo.com/series/icc-men-s-...
1,2,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825,https://www.espncricinfo.com/series/icc-men-s-...
2,3,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826,https://www.espncricinfo.com/series/icc-men-s-...
3,4,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828,https://www.espncricinfo.com/series/icc-men-s-...
4,5,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830,https://www.espncricinfo.com/series/icc-men-s-...

In [4]:
#Dropping the first column of the dataframe
matches_df.drop(columns=matches_df.columns[0], axis=1,  inplace=True)

In [5]:
batting_df.head()

,Unnamed: 0,match,team_inning,batting_pos,player_name,player_profile,out/not_out,run,balls,maiden,4s,6s,strike_rate
0,0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,https://www.espncricinfo.com/cricketers/michae...,c Pramod Madushan b Chameera,3,6,7,0,0,50.00
1,1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,https://www.espncricinfo.com/cricketers/divan-...,c Shanaka b Pramod Madushan,9,9,15,1,0,100.00
2,2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,https://www.espncricinfo.com/cricketers/jan-ni...,c †Mendis b Karunaratne,20,12,18,1,2,166.66
3,3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,https://www.espncricinfo.com/cricketers/stepha...,c DM de Silva b Pramod Madushan,26,24,49,2,0,108.33
4,4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus (c),https://www.espncricinfo.com/cricketers/gerhar...,c Gunathilaka b PWH de Silva,20,24,30,0,0,83.33

In [6]:
batting_df.drop(columns=batting_df.columns[0], axis=1,  inplace=True)

In [7]:
bowling_df.head()

,Unnamed: 0,match,bowling_team,bowler,bowler_profile,over,maiden,runs,wickets,economy,0s,4s,6s,wides,no_balls
0,0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,https://www.espncricinfo.com/cricketers/mahees...,4.0,0,23,1,5.75,7,0,0,2,0
1,1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,https://www.espncricinfo.com/cricketers/dushma...,4.0,0,39,1,9.75,6,3,1,2,0
2,2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,https://www.espncricinfo.com/cricketers/pramod...,4.0,0,37,2,9.25,6,3,1,0,0
3,3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,https://www.espncricinfo.com/cricketers/chamik...,4.0,0,36,1,9.00,7,3,1,1,0
4,4,Namibia Vs Sri Lanka,Sri Lanka,Wanindu Hasaranga,https://www.espncricinfo.com/cricketers/wanind...,4.0,0,27,1,6.75,8,1,1,0,0

In [8]:
bowling_df.drop(columns=bowling_df.columns[0], axis=1,  inplace=True)

In [9]:
#Creating an empty dictionary to store the match ids of all the matches as they will be unique for each match and will be used in connecting with other datas
match_id_dict = {}

for index, row in matches_df.iterrows(): 
    match_id_dict[f"{row['Team1']} Vs {row['Team2']}"] = row['Match_id']
    match_id_dict[f"{row['Team2']} Vs {row['Team1']}"] = row['Match_id']

In [10]:
# Replacing values of 'U.A.E.' with 'United Arab Emirates' as they may cause errors in future
temp = {}
for key, value in match_id_dict.items():
    if 'U.A.E.' in key:
        n= key.replace('U.A.E.',"United Arab Emirates" )
        temp[key] = n
        
for key, value in temp.items():
    match_id_dict[value] = match_id_dict.pop(key)

In [11]:
match_id_dict

{'Namibia Vs Sri Lanka': 'T20I # 1823',
 'Sri Lanka Vs Namibia': 'T20I # 1823',
 'Scotland Vs West Indies': 'T20I # 1826',
 'West Indies Vs Scotland': 'T20I # 1826',
 'Ireland Vs Zimbabwe': 'T20I # 1828',
 'Zimbabwe Vs Ireland': 'T20I # 1828',
 'Namibia Vs Netherlands': 'T20I # 1830',
 'Netherlands Vs Namibia': 'T20I # 1830',
 'Ireland Vs Scotland': 'T20I # 1833',
 'Scotland Vs Ireland': 'T20I # 1833',
 'West Indies Vs Zimbabwe': 'T20I # 1834',
 'Zimbabwe Vs West Indies': 'T20I # 1834',
 'Netherlands Vs Sri Lanka': 'T20I # 1835',
 'Sri Lanka Vs Netherlands': 'T20I # 1835',
 'Ireland Vs West Indies': 'T20I # 1837',
 'West Indies Vs Ireland': 'T20I # 1837',
 'Scotland Vs Zimbabwe': 'T20I # 1838',
 'Zimbabwe Vs Scotland': 'T20I # 1838',
 'Australia Vs New Zealand': 'T20I # 1839',
 'New Zealand Vs Australia': 'T20I # 1839',
 'Afghanistan Vs England': 'T20I # 1840',
 'England Vs Afghanistan': 'T20I # 1840',
 'Ireland Vs Sri Lanka': 'T20I # 1841',
 'Sri Lanka Vs Ireland': 'T20I # 1841',
 'India Vs Pakistan': 'T20I # 1842',
 'Pakistan Vs India': 'T20I # 1842',
 'Bangladesh Vs Netherlands': 'T20I # 1843',
 'Netherlands Vs Bangladesh': 'T20I # 1843',
 'South Africa Vs Zimbabwe': 'T20I # 1844',
 'Zimbabwe Vs South Africa': 'T20I # 1844',
 'Australia Vs Sri Lanka': 'T20I # 1845',
 'Sri Lanka Vs Australia': 'T20I # 1845',
 'England Vs Ireland': 'T20I # 1846',
 'Ireland Vs England': 'T20I # 1846',
 'Bangladesh Vs South Africa': 'T20I # 1847',
 'South Africa Vs Bangladesh': 'T20I # 1847',
 'India Vs Netherlands': 'T20I # 1848',
 'Netherlands Vs India': 'T20I # 1848',
 'Pakistan Vs Zimbabwe': 'T20I # 1849',
 'Zimbabwe Vs Pakistan': 'T20I # 1849',
 'New Zealand Vs Sri Lanka': 'T20I # 1850',
 'Sri Lanka Vs New Zealand': 'T20I # 1850',
 'Bangladesh Vs Zimbabwe': 'T20I # 1851',
 'Zimbabwe Vs Bangladesh': 'T20I # 1851',
 'Netherlands Vs Pakistan': 'T20I # 1852',
 'Pakistan Vs Netherlands': 'T20I # 1852',
 'India Vs South Africa': 'T20I # 1853',
 'South Africa Vs India': 'T20I # 1853',
 'Australia Vs Ireland': 'T20I # 1855',
 'Ireland Vs Australia': 'T20I # 1855',
 'Afghanistan Vs Sri Lanka': 'T20I # 1856',
 'Sri Lanka Vs Afghanistan': 'T20I # 1856',
 'England Vs New Zealand': 'T20I # 1858',
 'New Zealand Vs England': 'T20I # 1858',
 'Netherlands Vs Zimbabwe': 'T20I # 1859',
 'Zimbabwe Vs Netherlands': 'T20I # 1859',
 'Bangladesh Vs India': 'T20I # 1860',
 'India Vs Bangladesh': 'T20I # 1860',
 'Pakistan Vs South Africa': 'T20I # 1861',
 'South Africa Vs Pakistan': 'T20I # 1861',
 'Ireland Vs New Zealand': 'T20I # 1862',
 'New Zealand Vs Ireland': 'T20I # 1862',
 'Australia Vs Afghanistan': 'T20I # 1864',
 'Afghanistan Vs Australia': 'T20I # 1864',
 'England Vs Sri Lanka': 'T20I # 1867',
 'Sri Lanka Vs England': 'T20I # 1867',
 'Netherlands Vs South Africa': 'T20I # 1871',
 'South Africa Vs Netherlands': 'T20I # 1871',
 'Bangladesh Vs Pakistan': 'T20I # 1872',
 'Pakistan Vs Bangladesh': 'T20I # 1872',
 'India Vs Zimbabwe': 'T20I # 1873',
 'Zimbabwe Vs India': 'T20I # 1873',
 'New Zealand Vs Pakistan': 'T20I # 1877',
 'Pakistan Vs New Zealand': 'T20I # 1877',
 'England Vs India': 'T20I # 1878',
 'India Vs England': 'T20I # 1878',
 'England Vs Pakistan': 'T20I # 1879',
 'Pakistan Vs England': 'T20I # 1879',
 'Netherlands Vs United Arab Emirates': 'T20I # 1825',
 'United Arab Emirates Vs Netherlands': 'T20I # 1825',
 'Sri Lanka Vs United Arab Emirates': 'T20I # 1832',
 'United Arab Emirates Vs Sri Lanka': 'T20I # 1832',
 'Namibia Vs United Arab Emirates': 'T20I # 1836',
 'United Arab Emirates Vs Namibia': 'T20I # 1836'}

In [12]:
batting_df.head()

,match,team_inning,batting_pos,player_name,player_profile,out/not_out,run,balls,maiden,4s,6s,strike_rate
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,https://www.espncricinfo.com/cricketers/michae...,c Pramod Madushan b Chameera,3,6,7,0,0,50.00
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,https://www.espncricinfo.com/cricketers/divan-...,c Shanaka b Pramod Madushan,9,9,15,1,0,100.00
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,https://www.espncricinfo.com/cricketers/jan-ni...,c †Mendis b Karunaratne,20,12,18,1,2,166.66
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,https://www.espncricinfo.com/cricketers/stepha...,c DM de Silva b Pramod Madushan,26,24,49,2,0,108.33
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus (c),https://www.espncricinfo.com/cricketers/gerhar...,c Gunathilaka b PWH de Silva,20,24,30,0,0,83.33

In [13]:
# function to check and convert whether the player got Out or not
def out_not_out(string):
    if "not out" in string.lower():
        return "not out"
    else:
        return 'out'

In [14]:
#Applying the above function using .apply method
batting_df['out/not_out'] = batting_df['out/not_out'].apply(out_not_out)

In [15]:
batting_df.head()

,match,team_inning,batting_pos,player_name,player_profile,out/not_out,run,balls,maiden,4s,6s,strike_rate
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,https://www.espncricinfo.com/cricketers/michae...,out,3,6,7,0,0,50.00
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,https://www.espncricinfo.com/cricketers/divan-...,out,9,9,15,1,0,100.00
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,https://www.espncricinfo.com/cricketers/jan-ni...,out,20,12,18,1,2,166.66
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,https://www.espncricinfo.com/cricketers/stepha...,out,26,24,49,2,0,108.33
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus (c),https://www.espncricinfo.com/cricketers/gerhar...,out,20,24,30,0,0,83.33

In [16]:
batting_df['out/not_out'].unique()

array(['out', 'not out'], dtype=object)

In [17]:
#Mapping the values of match_id_dict and creating new column using the same
batting_df['match_id'] = batting_df['match'].map(match_id_dict)

In [18]:
batting_df.head()

,match,team_inning,batting_pos,player_name,player_profile,out/not_out,run,balls,maiden,4s,6s,strike_rate,match_id
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,https://www.espncricinfo.com/cricketers/michae...,out,3,6,7,0,0,50.00,T20I # 1823
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,https://www.espncricinfo.com/cricketers/divan-...,out,9,9,15,1,0,100.00,T20I # 1823
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,https://www.espncricinfo.com/cricketers/jan-ni...,out,20,12,18,1,2,166.66,T20I # 1823
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,https://www.espncricinfo.com/cricketers/stepha...,out,26,24,49,2,0,108.33,T20I # 1823
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus (c),https://www.espncricinfo.com/cricketers/gerhar...,out,20,24,30,0,0,83.33,T20I # 1823

In [19]:
len(batting_df['match_id'].unique())

42

In [20]:
bowling_df.head()

,match,bowling_team,bowler,bowler_profile,over,maiden,runs,wickets,economy,0s,4s,6s,wides,no_balls
0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,https://www.espncricinfo.com/cricketers/mahees...,4.0,0,23,1,5.75,7,0,0,2,0
1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,https://www.espncricinfo.com/cricketers/dushma...,4.0,0,39,1,9.75,6,3,1,2,0
2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,https://www.espncricinfo.com/cricketers/pramod...,4.0,0,37,2,9.25,6,3,1,0,0
3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,https://www.espncricinfo.com/cricketers/chamik...,4.0,0,36,1,9.00,7,3,1,1,0
4,Namibia Vs Sri Lanka,Sri Lanka,Wanindu Hasaranga,https://www.espncricinfo.com/cricketers/wanind...,4.0,0,27,1,6.75,8,1,1,0,0

In [21]:
bowling_df['match_id'] = bowling_df['match'].map(match_id_dict)

In [22]:
bowling_df.head()

,match,bowling_team,bowler,bowler_profile,over,maiden,runs,wickets,economy,0s,4s,6s,wides,no_balls,match_id
0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,https://www.espncricinfo.com/cricketers/mahees...,4.0,0,23,1,5.75,7,0,0,2,0,T20I # 1823
1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,https://www.espncricinfo.com/cricketers/dushma...,4.0,0,39,1,9.75,6,3,1,2,0,T20I # 1823
2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,https://www.espncricinfo.com/cricketers/pramod...,4.0,0,37,2,9.25,6,3,1,0,0,T20I # 1823
3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,https://www.espncricinfo.com/cricketers/chamik...,4.0,0,36,1,9.00,7,3,1,1,0,T20I # 1823
4,Namibia Vs Sri Lanka,Sri Lanka,Wanindu Hasaranga,https://www.espncricinfo.com/cricketers/wanind...,4.0,0,27,1,6.75,8,1,1,0,0,T20I # 1823

In [23]:
len(bowling_df['match_id'].unique())

42

In [24]:
# Creating new CSVs file of the updated dataframes
matches_df.to_csv('data/new_matches_data.csv')
batting_df.to_csv('data/new_batting_data.csv')
bowling_df.to_csv('data/new_bowling_data.csv')